# Generated by Django 5.2.17 on 2026-08-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='The number/code printed in the barcode on the product.', max_length=64, null=True, unique=True),
        ),
    ]
